Rmrk docs updates
rmrk-team/rmrk-docs pull request #4
Opened 2021-06-21 10:07 UTC by shibatales

2021-06-21 10:23 UTC, Swader requested changes
Good start but needs lots more love and work.

2021-06-21 10:23 UTC, Swader commented on docs/nfts.md
> +The following is a component that implements various tool examples using a previous json dump named `ConsolidatedRemarks` (with the working code equivalent commented out). In a nutshell, the componen
You can't refer to personal pronouns in docs. "My" has no meaning here. Remove personal angle please. 

Also, due to the evolving nature of external projects, I'd prefer if we didn't link to them from docs and risk making the content outdated asap. If you're documenting an example, if should be atomic, standalone, encapsulated, not depend on much else.

2021-06-21 10:23 UTC, Swader commented on docs/nfts.md
> +        // const api = await ApiPromise.create({ provider });
Commented parts of code are just confusing. Focus on the logic you're demonstrating only. Explain why, what it does, and what the point of this example is (what the reader learns).

2021-06-21 10:23 UTC, Swader commented on docs/nfts.md
> +### Methods and interfaces used
Does this mean anything to the new reader?

2021-06-21 10:23 UTC, Swader commented on docs/tools-cli.md
> +If you end up working with large data sets such as the latest dump from Singular, we recommend using the CLI tools to generate this json data for you, in case you experience a large CPU data spike wh
Link to latest dump.

2021-06-21 10:23 UTC, Swader commented on docs/tools-cli.md
> +- If you get a build error when you try using the cli helper tools, you need to make sure you install all of your dependencies (for me, it required that I install the dependencies `@polkadot/api` and
If we need these and they are not included, this is something to be flagged on the tools repo and fixed.

2021-06-21 10:23 UTC, Swader commented on docs/tools-cli.md
> +- For those working with latest dump data: if you run the cli:`fetch` method, and you are still trying to connect to the 127.0.0.1:9944 default endpoint, you need to run fetch with the optional param
Why?
If this is a tools bug / gaffe, it should be documented there and fixed. We don't want to document workarounds for bugs, not when we are the authors of the bugged tools.

2021-06-21 10:23 UTC, Swader commented on docs/tools-cli.md
> +Optional parameters for `fetch`:
You're missing escapes here:

\- --ws URL

vs

\- `--ws URL`


Also not sure this is really necessary - we'll keep the README of the tools up to date. By copying it here, you risk going out of date in two places.

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +This walkthrough of our Tools is based on the 1.0 spec. We will be releasing v2.0 docs whenever RMRK2.0 hits the shelves! For the best developer experience, we recommend developing with the most curr
> we recommend developing with the most current **Mac operating system**.

We absolutely do not, lol :D Remove please. Recommend a *nix environment, that's it.

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +### Warning: Not a stroll in the park
Unnecessary, why scare people away?

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +Getting RMRK Tools to run properly in local development is currently not a plug-and-play experience. You will need to be familiar with creating your first Substrate node using the Rust programming la
You can just download the Polkadot or Kusama binary and run it if on Ubuntu. The tutorial to do a compilation, though, is more like 10 minutes + 40 min compilation time.

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +Make sure to update to recent version of nvm/node 14.0+; if you're on Windows, nvm-windows has an installer (but again, I would like to reiterate that this tutorial is for Mac development only).
Again personal angle, please make more objective. Do not recommend any OS beyond using a *nix ecosystem: Ubuntu on Linux, Ubuntu on WSL if on Windows, OS X on Mac. That's all people need to know.

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +Make sure that in polkadot.js.org that you switch to the Development network using the custom endpoint: `wss://node.rmrk.app` or whatever local endpoint you decided on (press the Switch button at the
Don't recommend `node.rmrk.app` when mentioning dev environments, as people might take it to mean that's a dev endpoint.

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +You need to install `pallet-utility` in Cargo.toml under the runtime directory.
Skip this whole section, if they download and/or compile substrate-node, Polkadot, or Kusama, it's all taken care of.

2021-06-21 10:23 UTC, Swader commented on docs/tools-docs.md
> +If you want to test your UI with the latest data dump from Singular: [💩💩💩](https://gateway.pinata.cloud/ipns/latestdump.rmrk.app)
Let's be professional

```suggestion
If you want to test your UI with the [latest data dump from Singular](https://gateway.pinata.cloud/ipns/latestdump.rmrk.app)
```

2022-08-23 13:13 UTC, rdovgan approved these changes

2022-09-11 15:45 UTC, closed without merging

2022-09-11 15:45 UTC, Swader commented
This has kind of expired and the docs significantly changed since